version: '3.8'

services:
  backend:
    build: .
    container_name: react-echo-backend
    volumes:
      - '.:/go/app'
    ports:
      - '9090:9090'
    tty: true
    stdin_open: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - database_react-echo-sample
networks:
  database_react-echo-sample:
    external: true
