version: '3.8'

services:
  node:
    build: .
    container_name: react-echo-front
    volumes:
      - .:/var/www
    ports:
      - '3100:3000'
    tty: true
    environment:
      - NODE_ENV=development
    networks:
      - database_react-echo-sample
networks:
  database_react-echo-sample:
    external: true
